// REST API 애플리케이션
dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'
    implementation 'org.jsoup:jsoup:1.23.2'
    implementation 'com.twelvemonkeys.imageio:imageio-webp:3.15.0'
}
